title: Duplicate Remover
description: Add-On that given a set of documents will check their hash values for uniqueness and remove duplicates. You must be the owner of the documents to delete them from DocumentCloud.
instructions: ''
type: object
documents:
  - selected
  - query
properties:
  confirm:
    title: Please check this box if you are sure you want to remove duplicate documents.
    type: boolean
categories: 
  - file
version: 2
